package money

func AED(i int64) Money { return MustForge(i, "AED") }
func AFN(i int64) Money { return MustForge(i, "AFN") }
func ALL(i int64) Money { return MustForge(i, "ALL") }
func AMD(i int64) Money { return MustForge(i, "AMD") }
func ANG(i int64) Money { return MustForge(i, "ANG") }
func AOA(i int64) Money { return MustForge(i, "AOA") }
func ARS(i int64) Money { return MustForge(i, "ARS") }
func AUD(i int64) Money { return MustForge(i, "AUD") }
func AWG(i int64) Money { return MustForge(i, "AWG") }
func AZN(i int64) Money { return MustForge(i, "AZN") }
func BAM(i int64) Money { return MustForge(i, "BAM") }
func BBD(i int64) Money { return MustForge(i, "BBD") }
func BDT(i int64) Money { return MustForge(i, "BDT") }
func BGN(i int64) Money { return MustForge(i, "BGN") }
func BHD(i int64) Money { return MustForge(i, "BHD") }
func BIF(i int64) Money { return MustForge(i, "BIF") }
func BMD(i int64) Money { return MustForge(i, "BMD") }
func BND(i int64) Money { return MustForge(i, "BND") }
func BOB(i int64) Money { return MustForge(i, "BOB") }
func BRL(i int64) Money { return MustForge(i, "BRL") }
func BSD(i int64) Money { return MustForge(i, "BSD") }
func BTN(i int64) Money { return MustForge(i, "BTN") }
func BWP(i int64) Money { return MustForge(i, "BWP") }
func BYN(i int64) Money { return MustForge(i, "BYN") }
func BZD(i int64) Money { return MustForge(i, "BZD") }
func CAD(i int64) Money { return MustForge(i, "CAD") }
func CDF(i int64) Money { return MustForge(i, "CDF") }
func CHF(i int64) Money { return MustForge(i, "CHF") }
func CLF(i int64) Money { return MustForge(i, "CLF") }
func CLP(i int64) Money { return MustForge(i, "CLP") }
func CNY(i int64) Money { return MustForge(i, "CNY") }
func COP(i int64) Money { return MustForge(i, "COP") }
func CRC(i int64) Money { return MustForge(i, "CRC") }
func CUC(i int64) Money { return MustForge(i, "CUC") }
func CUP(i int64) Money { return MustForge(i, "CUP") }
func CVE(i int64) Money { return MustForge(i, "CVE") }
func CZK(i int64) Money { return MustForge(i, "CZK") }
func DJF(i int64) Money { return MustForge(i, "DJF") }
func DKK(i int64) Money { return MustForge(i, "DKK") }
func DOP(i int64) Money { return MustForge(i, "DOP") }
func DZD(i int64) Money { return MustForge(i, "DZD") }
func EGP(i int64) Money { return MustForge(i, "EGP") }
func ERN(i int64) Money { return MustForge(i, "ERN") }
func ETB(i int64) Money { return MustForge(i, "ETB") }
func EUR(i int64) Money { return MustForge(i, "EUR") }
func FJD(i int64) Money { return MustForge(i, "FJD") }
func FKP(i int64) Money { return MustForge(i, "FKP") }
func GBP(i int64) Money { return MustForge(i, "GBP") }
func GEL(i int64) Money { return MustForge(i, "GEL") }
func GGP(i int64) Money { return MustForge(i, "GGP") }
func GHS(i int64) Money { return MustForge(i, "GHS") }
func GIP(i int64) Money { return MustForge(i, "GIP") }
func GMD(i int64) Money { return MustForge(i, "GMD") }
func GNF(i int64) Money { return MustForge(i, "GNF") }
func GTQ(i int64) Money { return MustForge(i, "GTQ") }
func GYD(i int64) Money { return MustForge(i, "GYD") }
func HKD(i int64) Money { return MustForge(i, "HKD") }
func HNL(i int64) Money { return MustForge(i, "HNL") }
func HRK(i int64) Money { return MustForge(i, "HRK") }
func HTG(i int64) Money { return MustForge(i, "HTG") }
func HUF(i int64) Money { return MustForge(i, "HUF") }
func IDR(i int64) Money { return MustForge(i, "IDR") }
func ILS(i int64) Money { return MustForge(i, "ILS") }
func IMP(i int64) Money { return MustForge(i, "IMP") }
func INR(i int64) Money { return MustForge(i, "INR") }
func IQD(i int64) Money { return MustForge(i, "IQD") }
func IRR(i int64) Money { return MustForge(i, "IRR") }
func ISK(i int64) Money { return MustForge(i, "ISK") }
func JEP(i int64) Money { return MustForge(i, "JEP") }
func JMD(i int64) Money { return MustForge(i, "JMD") }
func JOD(i int64) Money { return MustForge(i, "JOD") }
func JPY(i int64) Money { return MustForge(i, "JPY") }
func KES(i int64) Money { return MustForge(i, "KES") }
func KGS(i int64) Money { return MustForge(i, "KGS") }
func KHR(i int64) Money { return MustForge(i, "KHR") }
func KMF(i int64) Money { return MustForge(i, "KMF") }
func KPW(i int64) Money { return MustForge(i, "KPW") }
func KRW(i int64) Money { return MustForge(i, "KRW") }
func KWD(i int64) Money { return MustForge(i, "KWD") }
func KYD(i int64) Money { return MustForge(i, "KYD") }
func KZT(i int64) Money { return MustForge(i, "KZT") }
func LAK(i int64) Money { return MustForge(i, "LAK") }
func LBP(i int64) Money { return MustForge(i, "LBP") }
func LKR(i int64) Money { return MustForge(i, "LKR") }
func LRD(i int64) Money { return MustForge(i, "LRD") }
func LSL(i int64) Money { return MustForge(i, "LSL") }
func LYD(i int64) Money { return MustForge(i, "LYD") }
func MAD(i int64) Money { return MustForge(i, "MAD") }
func MDL(i int64) Money { return MustForge(i, "MDL") }
func MGA(i int64) Money { return MustForge(i, "MGA") }
func MKD(i int64) Money { return MustForge(i, "MKD") }
func MMK(i int64) Money { return MustForge(i, "MMK") }
func MNT(i int64) Money { return MustForge(i, "MNT") }
func MOP(i int64) Money { return MustForge(i, "MOP") }
func MRO(i int64) Money { return MustForge(i, "MRO") }
func MUR(i int64) Money { return MustForge(i, "MUR") }
func MVR(i int64) Money { return MustForge(i, "MVR") }
func MWK(i int64) Money { return MustForge(i, "MWK") }
func MXN(i int64) Money { return MustForge(i, "MXN") }
func MYR(i int64) Money { return MustForge(i, "MYR") }
func MZN(i int64) Money { return MustForge(i, "MZN") }
func NAD(i int64) Money { return MustForge(i, "NAD") }
func NGN(i int64) Money { return MustForge(i, "NGN") }
func NIO(i int64) Money { return MustForge(i, "NIO") }
func NOK(i int64) Money { return MustForge(i, "NOK") }
func NPR(i int64) Money { return MustForge(i, "NPR") }
func NZD(i int64) Money { return MustForge(i, "NZD") }
func OMR(i int64) Money { return MustForge(i, "OMR") }
func PAB(i int64) Money { return MustForge(i, "PAB") }
func PEN(i int64) Money { return MustForge(i, "PEN") }
func PGK(i int64) Money { return MustForge(i, "PGK") }
func PHP(i int64) Money { return MustForge(i, "PHP") }
func PKR(i int64) Money { return MustForge(i, "PKR") }
func PLN(i int64) Money { return MustForge(i, "PLN") }
func PYG(i int64) Money { return MustForge(i, "PYG") }
func QAR(i int64) Money { return MustForge(i, "QAR") }
func RON(i int64) Money { return MustForge(i, "RON") }
func RSD(i int64) Money { return MustForge(i, "RSD") }
func RUB(i int64) Money { return MustForge(i, "RUB") }
func RWF(i int64) Money { return MustForge(i, "RWF") }
func SAR(i int64) Money { return MustForge(i, "SAR") }
func SBD(i int64) Money { return MustForge(i, "SBD") }
func SCR(i int64) Money { return MustForge(i, "SCR") }
func SDG(i int64) Money { return MustForge(i, "SDG") }
func SEK(i int64) Money { return MustForge(i, "SEK") }
func SGD(i int64) Money { return MustForge(i, "SGD") }
func SHP(i int64) Money { return MustForge(i, "SHP") }
func SLL(i int64) Money { return MustForge(i, "SLL") }
func SOS(i int64) Money { return MustForge(i, "SOS") }
func SRD(i int64) Money { return MustForge(i, "SRD") }
func SSP(i int64) Money { return MustForge(i, "SSP") }
func STD(i int64) Money { return MustForge(i, "STD") }
func SVC(i int64) Money { return MustForge(i, "SVC") }
func SYP(i int64) Money { return MustForge(i, "SYP") }
func SZL(i int64) Money { return MustForge(i, "SZL") }
func THB(i int64) Money { return MustForge(i, "THB") }
func TJS(i int64) Money { return MustForge(i, "TJS") }
func TMT(i int64) Money { return MustForge(i, "TMT") }
func TND(i int64) Money { return MustForge(i, "TND") }
func TOP(i int64) Money { return MustForge(i, "TOP") }
func TRY(i int64) Money { return MustForge(i, "TRY") }
func TTD(i int64) Money { return MustForge(i, "TTD") }
func TWD(i int64) Money { return MustForge(i, "TWD") }
func TZS(i int64) Money { return MustForge(i, "TZS") }
func UAH(i int64) Money { return MustForge(i, "UAH") }
func UGX(i int64) Money { return MustForge(i, "UGX") }
func USD(i int64) Money { return MustForge(i, "USD") }
func UYU(i int64) Money { return MustForge(i, "UYU") }
func UZS(i int64) Money { return MustForge(i, "UZS") }
func VES(i int64) Money { return MustForge(i, "VES") }
func VEF(i int64) Money { return MustForge(i, "VEF") }
func VND(i int64) Money { return MustForge(i, "VND") }
func VUV(i int64) Money { return MustForge(i, "VUV") }
func WST(i int64) Money { return MustForge(i, "WST") }
func XAF(i int64) Money { return MustForge(i, "XAF") }
func XOF(i int64) Money { return MustForge(i, "XOF") }
func XPF(i int64) Money { return MustForge(i, "XPF") }
func XCD(i int64) Money { return MustForge(i, "XCD") }
func YER(i int64) Money { return MustForge(i, "YER") }
func ZAR(i int64) Money { return MustForge(i, "ZAR") }
func ZMW(i int64) Money { return MustForge(i, "ZMW") }
func ZWD(i int64) Money { return MustForge(i, "ZWD") }
