package money

func FloatAED(i float64) Money { return MustForgeFloat(i, "AED") }
func FloatAFN(i float64) Money { return MustForgeFloat(i, "AFN") }
func FloatALL(i float64) Money { return MustForgeFloat(i, "ALL") }
func FloatAMD(i float64) Money { return MustForgeFloat(i, "AMD") }
func FloatANG(i float64) Money { return MustForgeFloat(i, "ANG") }
func FloatAOA(i float64) Money { return MustForgeFloat(i, "AOA") }
func FloatARS(i float64) Money { return MustForgeFloat(i, "ARS") }
func FloatAUD(i float64) Money { return MustForgeFloat(i, "AUD") }
func FloatAWG(i float64) Money { return MustForgeFloat(i, "AWG") }
func FloatAZN(i float64) Money { return MustForgeFloat(i, "AZN") }
func FloatBAM(i float64) Money { return MustForgeFloat(i, "BAM") }
func FloatBBD(i float64) Money { return MustForgeFloat(i, "BBD") }
func FloatBDT(i float64) Money { return MustForgeFloat(i, "BDT") }
func FloatBGN(i float64) Money { return MustForgeFloat(i, "BGN") }
func FloatBHD(i float64) Money { return MustForgeFloat(i, "BHD") }
func FloatBIF(i float64) Money { return MustForgeFloat(i, "BIF") }
func FloatBMD(i float64) Money { return MustForgeFloat(i, "BMD") }
func FloatBND(i float64) Money { return MustForgeFloat(i, "BND") }
func FloatBOB(i float64) Money { return MustForgeFloat(i, "BOB") }
func FloatBRL(i float64) Money { return MustForgeFloat(i, "BRL") }
func FloatBSD(i float64) Money { return MustForgeFloat(i, "BSD") }
func FloatBTN(i float64) Money { return MustForgeFloat(i, "BTN") }
func FloatBWP(i float64) Money { return MustForgeFloat(i, "BWP") }
func FloatBYN(i float64) Money { return MustForgeFloat(i, "BYN") }
func FloatBZD(i float64) Money { return MustForgeFloat(i, "BZD") }
func FloatCAD(i float64) Money { return MustForgeFloat(i, "CAD") }
func FloatCDF(i float64) Money { return MustForgeFloat(i, "CDF") }
func FloatCHF(i float64) Money { return MustForgeFloat(i, "CHF") }
func FloatCLF(i float64) Money { return MustForgeFloat(i, "CLF") }
func FloatCLP(i float64) Money { return MustForgeFloat(i, "CLP") }
func FloatCNY(i float64) Money { return MustForgeFloat(i, "CNY") }
func FloatCOP(i float64) Money { return MustForgeFloat(i, "COP") }
func FloatCRC(i float64) Money { return MustForgeFloat(i, "CRC") }
func FloatCUC(i float64) Money { return MustForgeFloat(i, "CUC") }
func FloatCUP(i float64) Money { return MustForgeFloat(i, "CUP") }
func FloatCVE(i float64) Money { return MustForgeFloat(i, "CVE") }
func FloatCZK(i float64) Money { return MustForgeFloat(i, "CZK") }
func FloatDJF(i float64) Money { return MustForgeFloat(i, "DJF") }
func FloatDKK(i float64) Money { return MustForgeFloat(i, "DKK") }
func FloatDOP(i float64) Money { return MustForgeFloat(i, "DOP") }
func FloatDZD(i float64) Money { return MustForgeFloat(i, "DZD") }
func FloatEGP(i float64) Money { return MustForgeFloat(i, "EGP") }
func FloatERN(i float64) Money { return MustForgeFloat(i, "ERN") }
func FloatETB(i float64) Money { return MustForgeFloat(i, "ETB") }
func FloatEUR(i float64) Money { return MustForgeFloat(i, "EUR") }
func FloatFJD(i float64) Money { return MustForgeFloat(i, "FJD") }
func FloatFKP(i float64) Money { return MustForgeFloat(i, "FKP") }
func FloatGBP(i float64) Money { return MustForgeFloat(i, "GBP") }
func FloatGEL(i float64) Money { return MustForgeFloat(i, "GEL") }
func FloatGGP(i float64) Money { return MustForgeFloat(i, "GGP") }
func FloatGHS(i float64) Money { return MustForgeFloat(i, "GHS") }
func FloatGIP(i float64) Money { return MustForgeFloat(i, "GIP") }
func FloatGMD(i float64) Money { return MustForgeFloat(i, "GMD") }
func FloatGNF(i float64) Money { return MustForgeFloat(i, "GNF") }
func FloatGTQ(i float64) Money { return MustForgeFloat(i, "GTQ") }
func FloatGYD(i float64) Money { return MustForgeFloat(i, "GYD") }
func FloatHKD(i float64) Money { return MustForgeFloat(i, "HKD") }
func FloatHNL(i float64) Money { return MustForgeFloat(i, "HNL") }
func FloatHRK(i float64) Money { return MustForgeFloat(i, "HRK") }
func FloatHTG(i float64) Money { return MustForgeFloat(i, "HTG") }
func FloatHUF(i float64) Money { return MustForgeFloat(i, "HUF") }
func FloatIDR(i float64) Money { return MustForgeFloat(i, "IDR") }
func FloatILS(i float64) Money { return MustForgeFloat(i, "ILS") }
func FloatIMP(i float64) Money { return MustForgeFloat(i, "IMP") }
func FloatINR(i float64) Money { return MustForgeFloat(i, "INR") }
func FloatIQD(i float64) Money { return MustForgeFloat(i, "IQD") }
func FloatIRR(i float64) Money { return MustForgeFloat(i, "IRR") }
func FloatISK(i float64) Money { return MustForgeFloat(i, "ISK") }
func FloatJEP(i float64) Money { return MustForgeFloat(i, "JEP") }
func FloatJMD(i float64) Money { return MustForgeFloat(i, "JMD") }
func FloatJOD(i float64) Money { return MustForgeFloat(i, "JOD") }
func FloatJPY(i float64) Money { return MustForgeFloat(i, "JPY") }
func FloatKES(i float64) Money { return MustForgeFloat(i, "KES") }
func FloatKGS(i float64) Money { return MustForgeFloat(i, "KGS") }
func FloatKHR(i float64) Money { return MustForgeFloat(i, "KHR") }
func FloatKMF(i float64) Money { return MustForgeFloat(i, "KMF") }
func FloatKPW(i float64) Money { return MustForgeFloat(i, "KPW") }
func FloatKRW(i float64) Money { return MustForgeFloat(i, "KRW") }
func FloatKWD(i float64) Money { return MustForgeFloat(i, "KWD") }
func FloatKYD(i float64) Money { return MustForgeFloat(i, "KYD") }
func FloatKZT(i float64) Money { return MustForgeFloat(i, "KZT") }
func FloatLAK(i float64) Money { return MustForgeFloat(i, "LAK") }
func FloatLBP(i float64) Money { return MustForgeFloat(i, "LBP") }
func FloatLKR(i float64) Money { return MustForgeFloat(i, "LKR") }
func FloatLRD(i float64) Money { return MustForgeFloat(i, "LRD") }
func FloatLSL(i float64) Money { return MustForgeFloat(i, "LSL") }
func FloatLYD(i float64) Money { return MustForgeFloat(i, "LYD") }
func FloatMAD(i float64) Money { return MustForgeFloat(i, "MAD") }
func FloatMDL(i float64) Money { return MustForgeFloat(i, "MDL") }
func FloatMGA(i float64) Money { return MustForgeFloat(i, "MGA") }
func FloatMKD(i float64) Money { return MustForgeFloat(i, "MKD") }
func FloatMMK(i float64) Money { return MustForgeFloat(i, "MMK") }
func FloatMNT(i float64) Money { return MustForgeFloat(i, "MNT") }
func FloatMOP(i float64) Money { return MustForgeFloat(i, "MOP") }
func FloatMRO(i float64) Money { return MustForgeFloat(i, "MRO") }
func FloatMUR(i float64) Money { return MustForgeFloat(i, "MUR") }
func FloatMVR(i float64) Money { return MustForgeFloat(i, "MVR") }
func FloatMWK(i float64) Money { return MustForgeFloat(i, "MWK") }
func FloatMXN(i float64) Money { return MustForgeFloat(i, "MXN") }
func FloatMYR(i float64) Money { return MustForgeFloat(i, "MYR") }
func FloatMZN(i float64) Money { return MustForgeFloat(i, "MZN") }
func FloatNAD(i float64) Money { return MustForgeFloat(i, "NAD") }
func FloatNGN(i float64) Money { return MustForgeFloat(i, "NGN") }
func FloatNIO(i float64) Money { return MustForgeFloat(i, "NIO") }
func FloatNOK(i float64) Money { return MustForgeFloat(i, "NOK") }
func FloatNPR(i float64) Money { return MustForgeFloat(i, "NPR") }
func FloatNZD(i float64) Money { return MustForgeFloat(i, "NZD") }
func FloatOMR(i float64) Money { return MustForgeFloat(i, "OMR") }
func FloatPAB(i float64) Money { return MustForgeFloat(i, "PAB") }
func FloatPEN(i float64) Money { return MustForgeFloat(i, "PEN") }
func FloatPGK(i float64) Money { return MustForgeFloat(i, "PGK") }
func FloatPHP(i float64) Money { return MustForgeFloat(i, "PHP") }
func FloatPKR(i float64) Money { return MustForgeFloat(i, "PKR") }
func FloatPLN(i float64) Money { return MustForgeFloat(i, "PLN") }
func FloatPYG(i float64) Money { return MustForgeFloat(i, "PYG") }
func FloatQAR(i float64) Money { return MustForgeFloat(i, "QAR") }
func FloatRON(i float64) Money { return MustForgeFloat(i, "RON") }
func FloatRSD(i float64) Money { return MustForgeFloat(i, "RSD") }
func FloatRUB(i float64) Money { return MustForgeFloat(i, "RUB") }
func FloatRWF(i float64) Money { return MustForgeFloat(i, "RWF") }
func FloatSAR(i float64) Money { return MustForgeFloat(i, "SAR") }
func FloatSBD(i float64) Money { return MustForgeFloat(i, "SBD") }
func FloatSCR(i float64) Money { return MustForgeFloat(i, "SCR") }
func FloatSDG(i float64) Money { return MustForgeFloat(i, "SDG") }
func FloatSEK(i float64) Money { return MustForgeFloat(i, "SEK") }
func FloatSGD(i float64) Money { return MustForgeFloat(i, "SGD") }
func FloatSHP(i float64) Money { return MustForgeFloat(i, "SHP") }
func FloatSLL(i float64) Money { return MustForgeFloat(i, "SLL") }
func FloatSOS(i float64) Money { return MustForgeFloat(i, "SOS") }
func FloatSRD(i float64) Money { return MustForgeFloat(i, "SRD") }
func FloatSSP(i float64) Money { return MustForgeFloat(i, "SSP") }
func FloatSTD(i float64) Money { return MustForgeFloat(i, "STD") }
func FloatSVC(i float64) Money { return MustForgeFloat(i, "SVC") }
func FloatSYP(i float64) Money { return MustForgeFloat(i, "SYP") }
func FloatSZL(i float64) Money { return MustForgeFloat(i, "SZL") }
func FloatTHB(i float64) Money { return MustForgeFloat(i, "THB") }
func FloatTJS(i float64) Money { return MustForgeFloat(i, "TJS") }
func FloatTMT(i float64) Money { return MustForgeFloat(i, "TMT") }
func FloatTND(i float64) Money { return MustForgeFloat(i, "TND") }
func FloatTOP(i float64) Money { return MustForgeFloat(i, "TOP") }
func FloatTRY(i float64) Money { return MustForgeFloat(i, "TRY") }
func FloatTTD(i float64) Money { return MustForgeFloat(i, "TTD") }
func FloatTWD(i float64) Money { return MustForgeFloat(i, "TWD") }
func FloatTZS(i float64) Money { return MustForgeFloat(i, "TZS") }
func FloatUAH(i float64) Money { return MustForgeFloat(i, "UAH") }
func FloatUGX(i float64) Money { return MustForgeFloat(i, "UGX") }
func FloatUSD(i float64) Money { return MustForgeFloat(i, "USD") }
func FloatUYU(i float64) Money { return MustForgeFloat(i, "UYU") }
func FloatUZS(i float64) Money { return MustForgeFloat(i, "UZS") }
func FloatVES(i float64) Money { return MustForgeFloat(i, "VES") }
func FloatVEF(i float64) Money { return MustForgeFloat(i, "VEF") }
func FloatVND(i float64) Money { return MustForgeFloat(i, "VND") }
func FloatVUV(i float64) Money { return MustForgeFloat(i, "VUV") }
func FloatWST(i float64) Money { return MustForgeFloat(i, "WST") }
func FloatXAF(i float64) Money { return MustForgeFloat(i, "XAF") }
func FloatXOF(i float64) Money { return MustForgeFloat(i, "XOF") }
func FloatXPF(i float64) Money { return MustForgeFloat(i, "XPF") }
func FloatXCD(i float64) Money { return MustForgeFloat(i, "XCD") }
func FloatYER(i float64) Money { return MustForgeFloat(i, "YER") }
func FloatZAR(i float64) Money { return MustForgeFloat(i, "ZAR") }
func FloatZMW(i float64) Money { return MustForgeFloat(i, "ZMW") }
func FloatZWD(i float64) Money { return MustForgeFloat(i, "ZWD") }
